http_port: 9090
mysql:
  hostname: localhost
  port: 4306
  username: xanthing_dev
  password: pass_xanthing1234
  database: xanthing
  charset: utf8mb4
  maxIdleConns: 10 # 设置空闲连接池中连接的最大数量
  maxOpenConns: 100 # 设置打开数据库连接的最大数量


redis:
  addr: "localhost:6379"
  db: 0
  auth: test
